# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='informationNumber',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
