# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20160913_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
