# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20160913_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='grouping',
            field=models.CharField(choices=[('request', 'request'), ('offer', 'offer')], max_length=10),
        ),
    ]
