# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20160916_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('organization', 'Organization'), ('individual', 'Individual')], max_length=75),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(blank=True, choices=[('health', 'health/first aid'), ('durable', 'durable goods'), ('nondurable', 'non-durable goods'), ('perishable', 'perishable food items'), ('nonperishable', 'non-perishable food items'), ('volunteer', 'volunteer services')], max_length=75),
        ),
        migrations.AlterField(
            model_name='request',
            name='grouping',
            field=models.CharField(blank=True, choices=[('request', 'request'), ('offer', 'offer')], max_length=10),
        ),
    ]
